### ISSUE TITLE
Throw exception the application was started into docker container

### ISSUE THREAD

**Issue by vik-borisov** [dapplo/Dapplo.Log#1]
> System.TypeInitializationException: The type initializer for 'Dapplo.HttpExtensions.HttpExtensionsGlobals' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Dapplo.HttpExtensions.ContentConverter.ByteArrayHttpContentConverter' threw an exception. ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
> Parameter name: length
>    at System.String.Substring(Int32 startIndex, Int32 length)
>    at Dapplo.Log.LogSource..ctor(String sourceFilePath)
>    at Dapplo.HttpExtensions.ContentConverter.ByteArrayHttpContentConverter..cctor()
>    --- End of inner exception stack trace ---
>    at Dapplo.HttpExtensions.ContentConverter.ByteArrayHttpContentConverter.getInstance()
>    at Dapplo.HttpExtensions.HttpExtensionsGlobals..cctor()
>    --- End of inner exception stack trace ---
>    at Dapplo.HttpExtensions.HttpBehaviour..ctor()
>    at Dapplo.Jira.JiraClient..ctor(Uri baseUri, IHttpSettings httpSettings)
>    at Dapplo.Jira.JiraClient.Create(Uri baseUri, IHttpSettings httpSettings)

Docker image **microsoft/dotnet:latest**

**Comment by vik-borisov** [comment]
For example, NLog not require callerFilePath
https://github.com/NLog/NLog/blob/master/src/NLog/Fluent/Log.cs#L118

**Comment by vik-borisov** [comment]
I repeat exception:

Program:

> public static void LogSource([CallerFilePath] string sourceFilePath = null)
>         {
>             if (sourceFilePath == null)
>             {
>                 throw new ArgumentNullException(nameof(sourceFilePath));
>             }
> 
>             Console.WriteLine("sourceFilePath:" + sourceFilePath);
> 
> 			var directorySeparatorChar = Path.DirectorySeparatorChar;
>             Console.WriteLine("separator: " + directorySeparatorChar);
> 
>             var pathParts = sourceFilePath.Split(directorySeparatorChar);
> 
>             var typeName = Path.GetFileNameWithoutExtension(pathParts.Last());
>             var leftovers = sourceFilePath.Substring(0, sourceFilePath.LastIndexOf(typeName, StringComparison.Ordinal) - 1);
>             var nameSpace = Path.GetFileName(leftovers);
> 
>             var fqTypeName = $"{nameSpace}.{typeName}";
> 			var type = Type.GetType(fqTypeName, false, true);
>         }
> 
>         static void Main(string[] args)
>         {
>             Console.WriteLine("Hello World!");
> 
>             LogSource();
>         }

Result:

> sourceFilePath:E:\ConsoleApp1\ConsoleApp1\Program.cs
> separator: /
> 
>  Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
> Parameter name: length
>    at System.String.Substring(Int32 startIndex, Int32 length)
>    at ConsoleApp1.Program.LogSource(String sourceFilePath)
>    at ConsoleApp1.Program.Main(String[] args)
> Aborted

**Comment by vik-borisov** [comment]
I compiled program by Linux and got same exception:

> System.TypeInitializationException: The type initializer for 'Dapplo.HttpExtensions.HttpExtensionsGlobals' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Dapplo.HttpExtensions.ContentConverter.ByteArrayHttpContentConverter' threw an exception. ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
> Parameter name: length
>    at System.String.Substring(Int32 startIndex, Int32 length)
>    at Dapplo.Log.LogSource..ctor(String sourceFilePath)
>    at Dapplo.HttpExtensions.ContentConverter.ByteArrayHttpContentConverter..cctor()
>    --- End of inner exception stack trace ---
>    at Dapplo.HttpExtensions.ContentConverter.ByteArrayHttpContentConverter.getInstance()
>    at Dapplo.HttpExtensions.HttpExtensionsGlobals..cctor()
>    --- End of inner exception stack trace ---
>    at Dapplo.HttpExtensions.HttpBehaviour..ctor()
>    at Dapplo.Jira.JiraClient..ctor(Uri baseUri, IHttpSettings httpSettings)
>    at Dapplo.Jira.JiraClient.Create(Uri baseUri, IHttpSettings httpSettings)

**Comment by Lakritzator** [comment]
Thanks, very interesting. 😄
I will merge your PR.

**Comment by Lakritzator** [comment]
I'm actually not very sure if this was the best way to fix this, but it work for me. Thanks.

**Comment by vik-borisov** [comment]
Yep, it isn't the best way.  IMHO, finding a type by file path is wrong way. Maybe it is better to pass a type by a constructor parameter or by a generic parameter.
